const products = [
  {
    "id": 1,
    "name": "Pasta masala (rakesh)",
    "category": "Home Needs",
    "price": 4.0,
    "originalPrice": 4.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 297,
    "bestseller": false,
    "featured": false,
    "description": "Pasta masala (rakesh) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 2,
    "name": "Dettol original soap",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 348,
    "bestseller": false,
    "featured": false,
    "description": "Dettol original soap is a reliable and good quality product for everyday use.",
    "unit": "l"
  },
  {
    "id": 3,
    "name": "Lux soap",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 115,
    "bestseller": false,
    "featured": false,
    "description": "Lux soap is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 4,
    "name": "Lifebuoy soap",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 183,
    "bestseller": false,
    "featured": false,
    "description": "Lifebuoy soap is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 5,
    "name": "Surf excel soap",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 204,
    "bestseller": false,
    "featured": false,
    "description": "Surf excel soap is a reliable and good quality product for everyday use.",
    "unit": "l"
  },
  {
    "id": 6,
    "name": "Closeup toothpaste",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 118,
    "bestseller": false,
    "featured": false,
    "description": "Closeup toothpaste is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 7,
    "name": "Maggi noodles",
    "category": "Home Needs",
    "price": 7.0,
    "originalPrice": 7.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 138,
    "bestseller": false,
    "featured": false,
    "description": "Maggi noodles is a reliable and good quality product for everyday use.",
    "unit": "packet"
  },
  {
    "id": 8,
    "name": "Dabur toothpowder",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 262,
    "bestseller": false,
    "featured": false,
    "description": "Dabur toothpowder is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 9,
    "name": "Nihar gold hair oil",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 176,
    "bestseller": false,
    "featured": false,
    "description": "Nihar gold hair oil is a reliable and good quality product for everyday use.",
    "unit": "bottle"
  },
  {
    "id": 10,
    "name": "Tata iodised salt",
    "category": "Home Needs",
    "price": 30.0,
    "originalPrice": 30.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 473,
    "bestseller": false,
    "featured": false,
    "description": "Tata iodised salt is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 11,
    "name": "Goyal gold salt 500g",
    "category": "Home Needs",
    "price": 5.0,
    "originalPrice": 5.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 133,
    "bestseller": false,
    "featured": false,
    "description": "Goyal gold salt 500g is a reliable and good quality product for everyday use.",
    "unit": "l"
  },
  {
    "id": 12,
    "name": "based hair color",
    "category": "Home Needs",
    "price": 20.0,
    "originalPrice": 20.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 418,
    "bestseller": false,
    "featured": false,
    "description": "based hair color is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 13,
    "name": "Whole garam masala",
    "category": "Home Needs",
    "price": 5.0,
    "originalPrice": 5.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 222,
    "bestseller": false,
    "featured": false,
    "description": "Whole garam masala is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 14,
    "name": "Laxmanrekhaa",
    "category": "Home Needs",
    "price": 20.0,
    "originalPrice": 20.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 199,
    "bestseller": false,
    "featured": false,
    "description": "Laxmanrekhaa is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 15,
    "name": "lambu",
    "category": "Home Needs",
    "price": 5.0,
    "originalPrice": 5.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 222,
    "bestseller": false,
    "featured": false,
    "description": "lambu is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 16,
    "name": "Director pan-masala",
    "category": "Home Needs",
    "price": 12.0,
    "originalPrice": 12.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 105,
    "bestseller": false,
    "featured": false,
    "description": "Director pan-masala is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 17,
    "name": "Milk (sudha) 500ml",
    "category": "Home Needs",
    "price": 30.0,
    "originalPrice": 30.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 227,
    "bestseller": false,
    "featured": false,
    "description": "Milk (sudha) 500ml is a reliable and good quality product for everyday use.",
    "unit": "ml"
  },
  {
    "id": 18,
    "name": "Masoor dal (small)",
    "category": "Home Needs",
    "price": 100.0,
    "originalPrice": 100.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 153,
    "bestseller": false,
    "featured": false,
    "description": "Masoor dal (small) is a reliable and good quality product for everyday use.",
    "unit": "l"
  },
  {
    "id": 19,
    "name": "Taaza tea",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 164,
    "bestseller": false,
    "featured": false,
    "description": "Taaza tea is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 20,
    "name": "Surf excel surf 75g",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 449,
    "bestseller": false,
    "featured": false,
    "description": "Surf excel surf 75g is a reliable and good quality product for everyday use.",
    "unit": "l"
  },
  {
    "id": 21,
    "name": "Sugar",
    "category": "Home Needs",
    "price": 48.0,
    "originalPrice": 48.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 418,
    "bestseller": false,
    "featured": false,
    "description": "Sugar is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 22,
    "name": "Mishri",
    "category": "Home Needs",
    "price": 70.0,
    "originalPrice": 70.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 168,
    "bestseller": false,
    "featured": false,
    "description": "Mishri is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 23,
    "name": "Mentho plus",
    "category": "Home Needs",
    "price": 2.0,
    "originalPrice": 2.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 220,
    "bestseller": false,
    "featured": false,
    "description": "Mentho plus is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 24,
    "name": "Coolex toothbrush",
    "category": "Home Needs",
    "price": 30.0,
    "originalPrice": 30.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 172,
    "bestseller": false,
    "featured": false,
    "description": "Coolex toothbrush is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 25,
    "name": "Navaratna oil",
    "category": "Home Needs",
    "price": 1.0,
    "originalPrice": 1.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 410,
    "bestseller": false,
    "featured": false,
    "description": "Navaratna oil is a reliable and good quality product for everyday use.",
    "unit": "bottle"
  },
  {
    "id": 26,
    "name": "Himgange oil",
    "category": "Home Needs",
    "price": 1.0,
    "originalPrice": 1.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 359,
    "bestseller": false,
    "featured": false,
    "description": "Himgange oil is a reliable and good quality product for everyday use.",
    "unit": "bottle"
  },
  {
    "id": 27,
    "name": "Milk (sudha) 1liter",
    "category": "Home Needs",
    "price": 58.0,
    "originalPrice": 58.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 221,
    "bestseller": false,
    "featured": false,
    "description": "Milk (sudha) 1liter is a reliable and good quality product for everyday use.",
    "unit": "l"
  },
  {
    "id": 28,
    "name": "Dahi 80g (sudha)",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 281,
    "bestseller": false,
    "featured": false,
    "description": "Dahi 80g (sudha) is a reliable and good quality product for everyday use.",
    "unit": "g"
  },
  {
    "id": 29,
    "name": "Lassi 140ml (sudha)",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 201,
    "bestseller": false,
    "featured": false,
    "description": "Lassi 140ml (sudha) is a reliable and good quality product for everyday use.",
    "unit": "l"
  },
  {
    "id": 30,
    "name": "Maaza 125ml",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 175,
    "bestseller": false,
    "featured": false,
    "description": "Maaza 125ml is a reliable and good quality product for everyday use.",
    "unit": "ml"
  },
  {
    "id": 31,
    "name": "Besleri 500ml water",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 386,
    "bestseller": false,
    "featured": false,
    "description": "Besleri 500ml water is a reliable and good quality product for everyday use.",
    "unit": "l"
  },
  {
    "id": 32,
    "name": "Besleri 1000ml",
    "category": "Home Needs",
    "price": 20.0,
    "originalPrice": 20.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 440,
    "bestseller": false,
    "featured": false,
    "description": "Besleri 1000ml is a reliable and good quality product for everyday use.",
    "unit": "ml"
  },
  {
    "id": 33,
    "name": "Rabri 80g (sudha)",
    "category": "Home Needs",
    "price": 20.0,
    "originalPrice": 20.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 358,
    "bestseller": false,
    "featured": false,
    "description": "Rabri 80g (sudha) is a reliable and good quality product for everyday use.",
    "unit": "g"
  },
  {
    "id": 34,
    "name": "Jaggery (gur)",
    "category": "Home Needs",
    "price": 60.0,
    "originalPrice": 60.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 115,
    "bestseller": false,
    "featured": false,
    "description": "Jaggery (gur) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 35,
    "name": "Silver pearls",
    "category": "Home Needs",
    "price": 1.0,
    "originalPrice": 1.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 138,
    "bestseller": false,
    "featured": false,
    "description": "Silver pearls is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 36,
    "name": "Raj niwas pan-masala",
    "category": "Home Needs",
    "price": 6.0,
    "originalPrice": 6.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 306,
    "bestseller": false,
    "featured": false,
    "description": "Raj niwas pan-masala is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 37,
    "name": "Vimal pan-masala",
    "category": "Home Needs",
    "price": 6.0,
    "originalPrice": 6.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 124,
    "bestseller": false,
    "featured": false,
    "description": "Vimal pan-masala is a reliable and good quality product for everyday use.",
    "unit": "l"
  },
  {
    "id": 38,
    "name": "Shikhar pan-masala",
    "category": "Home Needs",
    "price": 6.0,
    "originalPrice": 6.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 239,
    "bestseller": false,
    "featured": false,
    "description": "Shikhar pan-masala is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 39,
    "name": "Gold flake cigarette",
    "category": "Home Needs",
    "price": 12.0,
    "originalPrice": 12.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 309,
    "bestseller": false,
    "featured": false,
    "description": "Gold flake cigarette is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 40,
    "name": "Charms cigarette",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 383,
    "bestseller": false,
    "featured": false,
    "description": "Charms cigarette is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 41,
    "name": "Kurkure",
    "category": "Home Needs",
    "price": 5.0,
    "originalPrice": 5.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 139,
    "bestseller": false,
    "featured": false,
    "description": "Kurkure is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 42,
    "name": "Takatak",
    "category": "Home Needs",
    "price": 5.0,
    "originalPrice": 5.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 367,
    "bestseller": false,
    "featured": false,
    "description": "Takatak is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 43,
    "name": "Diamond katori",
    "category": "Home Needs",
    "price": 5.0,
    "originalPrice": 5.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 497,
    "bestseller": false,
    "featured": false,
    "description": "Diamond katori is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 44,
    "name": "Lays chips (green)",
    "category": "Home Needs",
    "price": 5.0,
    "originalPrice": 5.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 113,
    "bestseller": false,
    "featured": false,
    "description": "Lays chips (green) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 45,
    "name": "Haldiram bhujia",
    "category": "Home Needs",
    "price": 5.0,
    "originalPrice": 5.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 343,
    "bestseller": false,
    "featured": false,
    "description": "Haldiram bhujia is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 46,
    "name": "Gme diet chiwda",
    "category": "Home Needs",
    "price": 5.0,
    "originalPrice": 5.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 251,
    "bestseller": false,
    "featured": false,
    "description": "Gme diet chiwda is a reliable and good quality product for everyday use.",
    "unit": "g"
  },
  {
    "id": 47,
    "name": "Hajmola (regular)",
    "category": "Home Needs",
    "price": 1.0,
    "originalPrice": 1.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 121,
    "bestseller": false,
    "featured": false,
    "description": "Hajmola (regular) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 48,
    "name": "Hajmola (chat-cola)",
    "category": "Home Needs",
    "price": 1.0,
    "originalPrice": 1.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 291,
    "bestseller": false,
    "featured": false,
    "description": "Hajmola (chat-cola) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 49,
    "name": "Panchphoran",
    "category": "Home Needs",
    "price": 5.0,
    "originalPrice": 5.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 256,
    "bestseller": false,
    "featured": false,
    "description": "Panchphoran is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 50,
    "name": "Meat masala (rakesh)",
    "category": "Home Needs",
    "price": 5.0,
    "originalPrice": 5.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 133,
    "bestseller": false,
    "featured": false,
    "description": "Meat masala (rakesh) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 51,
    "name": "Sabzi masala (rakesh)",
    "category": "Home Needs",
    "price": 5.0,
    "originalPrice": 5.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 356,
    "bestseller": false,
    "featured": false,
    "description": "Sabzi masala (rakesh) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 52,
    "name": "Potato (1kg)",
    "category": "Home Needs",
    "price": 15.0,
    "originalPrice": 15.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 208,
    "bestseller": false,
    "featured": false,
    "description": "Potato (1kg) is a reliable and good quality product for everyday use.",
    "unit": "kg"
  },
  {
    "id": 53,
    "name": "Onion (2.5kg)",
    "category": "Home Needs",
    "price": 60.0,
    "originalPrice": 60.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 160,
    "bestseller": false,
    "featured": false,
    "description": "Onion (2.5kg) is a reliable and good quality product for everyday use.",
    "unit": "kg"
  },
  {
    "id": 54,
    "name": "pure mustard oil",
    "category": "Home Needs",
    "price": 170.0,
    "originalPrice": 170.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 401,
    "bestseller": false,
    "featured": false,
    "description": "pure mustard oil is a reliable and good quality product for everyday use.",
    "unit": "bottle"
  },
  {
    "id": 55,
    "name": "Lighter",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 173,
    "bestseller": false,
    "featured": false,
    "description": "Lighter is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 56,
    "name": "Stove lighter",
    "category": "Home Needs",
    "price": 20.0,
    "originalPrice": 20.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 492,
    "bestseller": false,
    "featured": false,
    "description": "Stove lighter is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 57,
    "name": "Tap",
    "category": "Home Needs",
    "price": 20.0,
    "originalPrice": 20.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 204,
    "bestseller": false,
    "featured": false,
    "description": "Tap is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 58,
    "name": "Tata tea agni",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 391,
    "bestseller": false,
    "featured": false,
    "description": "Tata tea agni is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 59,
    "name": "Colgate",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 171,
    "bestseller": false,
    "featured": false,
    "description": "Colgate is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 60,
    "name": "Dove shampoo",
    "category": "Home Needs",
    "price": 2.0,
    "originalPrice": 2.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 408,
    "bestseller": false,
    "featured": false,
    "description": "Dove shampoo is a reliable and good quality product for everyday use.",
    "unit": "bottle"
  },
  {
    "id": 61,
    "name": "Clinic plus shampoo",
    "category": "Home Needs",
    "price": 1.0,
    "originalPrice": 1.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 184,
    "bestseller": false,
    "featured": false,
    "description": "Clinic plus shampoo is a reliable and good quality product for everyday use.",
    "unit": "bottle"
  },
  {
    "id": 62,
    "name": "Papad (choudhary)",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 398,
    "bestseller": false,
    "featured": false,
    "description": "Papad (choudhary) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 63,
    "name": "Sabu dana (sabu)",
    "category": "Home Needs",
    "price": 25.0,
    "originalPrice": 25.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 289,
    "bestseller": false,
    "featured": false,
    "description": "Sabu dana (sabu) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 64,
    "name": "2in1 biscuit (anmol)",
    "category": "Home Needs",
    "price": 5.0,
    "originalPrice": 5.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 341,
    "bestseller": false,
    "featured": false,
    "description": "2in1 biscuit (anmol) is a reliable and good quality product for everyday use.",
    "unit": "packet"
  },
  {
    "id": 65,
    "name": "anti-mosquito",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 227,
    "bestseller": false,
    "featured": false,
    "description": "anti-mosquito is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 66,
    "name": "Onion (1kg)",
    "category": "Home Needs",
    "price": 25.0,
    "originalPrice": 25.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 306,
    "bestseller": false,
    "featured": false,
    "description": "Onion (1kg) is a reliable and good quality product for everyday use.",
    "unit": "kg"
  },
  {
    "id": 67,
    "name": "Potato red (2.5kg)",
    "category": "Home Needs",
    "price": 35.0,
    "originalPrice": 35.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 187,
    "bestseller": false,
    "featured": false,
    "description": "Potato red (2.5kg) is a reliable and good quality product for everyday use.",
    "unit": "kg"
  },
  {
    "id": 68,
    "name": "Wheel surf 500g",
    "category": "Home Needs",
    "price": 39.0,
    "originalPrice": 39.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 216,
    "bestseller": false,
    "featured": false,
    "description": "Wheel surf 500g is a reliable and good quality product for everyday use.",
    "unit": "l"
  },
  {
    "id": 69,
    "name": "Chana dal",
    "category": "Home Needs",
    "price": 90.0,
    "originalPrice": 90.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 122,
    "bestseller": false,
    "featured": false,
    "description": "Chana dal is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 70,
    "name": "Electric tape",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 500,
    "bestseller": false,
    "featured": false,
    "description": "Electric tape is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 71,
    "name": "Ginger 100g",
    "category": "Home Needs",
    "price": 15.0,
    "originalPrice": 15.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 323,
    "bestseller": false,
    "featured": false,
    "description": "Ginger 100g is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 72,
    "name": "Jeera (loose) 100g",
    "category": "Home Needs",
    "price": 40.0,
    "originalPrice": 40.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 161,
    "bestseller": false,
    "featured": false,
    "description": "Jeera (loose) 100g is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 73,
    "name": "Sprite 250ml",
    "category": "Home Needs",
    "price": 22.0,
    "originalPrice": 22.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 180,
    "bestseller": false,
    "featured": false,
    "description": "Sprite 250ml is a reliable and good quality product for everyday use.",
    "unit": "ml"
  },
  {
    "id": 74,
    "name": "Paneer Dosha 1 plate",
    "category": "Home Needs",
    "price": 120.0,
    "originalPrice": 120.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 396,
    "bestseller": false,
    "featured": false,
    "description": "Paneer Dosha 1 plate is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 75,
    "name": "Jeera",
    "category": "Home Needs",
    "price": 400.0,
    "originalPrice": 400.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 283,
    "bestseller": false,
    "featured": false,
    "description": "Jeera is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 76,
    "name": "Ushna chawal 1kg",
    "category": "Home Needs",
    "price": 30.0,
    "originalPrice": 30.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 105,
    "bestseller": false,
    "featured": false,
    "description": "Ushna chawal 1kg is a reliable and good quality product for everyday use.",
    "unit": "kg"
  },
  {
    "id": 77,
    "name": "Butter Tawa Roti",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 141,
    "bestseller": false,
    "featured": false,
    "description": "Butter Tawa Roti is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 78,
    "name": "Egg",
    "category": "Home Needs",
    "price": 8.0,
    "originalPrice": 8.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 174,
    "bestseller": false,
    "featured": false,
    "description": "Egg is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 79,
    "name": "Dalmia gold tea 250g",
    "category": "Home Needs",
    "price": 135.0,
    "originalPrice": 135.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 243,
    "bestseller": false,
    "featured": false,
    "description": "Dalmia gold tea 250g is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 80,
    "name": "Surf excel surf 1kg",
    "category": "Home Needs",
    "price": 136.0,
    "originalPrice": 136.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 428,
    "bestseller": false,
    "featured": false,
    "description": "Surf excel surf 1kg is a reliable and good quality product for everyday use.",
    "unit": "kg"
  },
  {
    "id": 81,
    "name": "Harpic 500ml",
    "category": "Home Needs",
    "price": 110.0,
    "originalPrice": 110.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 345,
    "bestseller": false,
    "featured": false,
    "description": "Harpic 500ml is a reliable and good quality product for everyday use.",
    "unit": "ml"
  },
  {
    "id": 82,
    "name": "Holi balloon",
    "category": "Home Needs",
    "price": 5.0,
    "originalPrice": 5.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 206,
    "bestseller": false,
    "featured": false,
    "description": "Holi balloon is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 83,
    "name": "Roohafza 750ml",
    "category": "Home Needs",
    "price": 165.0,
    "originalPrice": 165.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 165,
    "bestseller": false,
    "featured": false,
    "description": "Roohafza 750ml is a reliable and good quality product for everyday use.",
    "unit": "ml"
  },
  {
    "id": 84,
    "name": "Mutton (Kalluji)",
    "category": "Home Needs",
    "price": 700.0,
    "originalPrice": 700.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 449,
    "bestseller": false,
    "featured": false,
    "description": "Mutton (Kalluji) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 85,
    "name": "Ganesh bhog atta",
    "category": "Home Needs",
    "price": 700.0,
    "originalPrice": 700.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 451,
    "bestseller": false,
    "featured": false,
    "description": "Ganesh bhog atta is a reliable and good quality product for everyday use.",
    "unit": "g"
  },
  {
    "id": 86,
    "name": "24 carat (LDM)",
    "category": "Home Needs",
    "price": 1.0,
    "originalPrice": 1.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 374,
    "bestseller": false,
    "featured": false,
    "description": "24 carat (LDM) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 87,
    "name": "Kerao dal",
    "category": "Home Needs",
    "price": 60.0,
    "originalPrice": 60.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 226,
    "bestseller": false,
    "featured": false,
    "description": "Kerao dal is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 88,
    "name": "Kerao besan 500g",
    "category": "Home Needs",
    "price": 40.0,
    "originalPrice": 40.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 202,
    "bestseller": false,
    "featured": false,
    "description": "Kerao besan 500g is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 89,
    "name": "Raw Chicken",
    "category": "Home Needs",
    "price": 170.0,
    "originalPrice": 170.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 498,
    "bestseller": false,
    "featured": false,
    "description": "Raw Chicken is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 90,
    "name": "Banana 6pcs",
    "category": "Home Needs",
    "price": 30.0,
    "originalPrice": 30.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 230,
    "bestseller": false,
    "featured": false,
    "description": "Banana 6pcs is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 91,
    "name": "Ghee",
    "category": "Home Needs",
    "price": 640.0,
    "originalPrice": 640.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 172,
    "bestseller": false,
    "featured": false,
    "description": "Ghee is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 92,
    "name": "Gulal",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 413,
    "bestseller": false,
    "featured": false,
    "description": "Gulal is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 93,
    "name": "Maida",
    "category": "Home Needs",
    "price": 40.0,
    "originalPrice": 40.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 210,
    "bestseller": false,
    "featured": false,
    "description": "Maida is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 94,
    "name": "Tejpatta",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 252,
    "bestseller": false,
    "featured": false,
    "description": "Tejpatta is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 95,
    "name": "Paneer 200g (sudha)",
    "category": "Home Needs",
    "price": 85.0,
    "originalPrice": 85.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 310,
    "bestseller": false,
    "featured": false,
    "description": "Paneer 200g (sudha) is a reliable and good quality product for everyday use.",
    "unit": "g"
  },
  {
    "id": 96,
    "name": "Rang packet",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 253,
    "bestseller": false,
    "featured": false,
    "description": "Rang packet is a reliable and good quality product for everyday use.",
    "unit": "g"
  },
  {
    "id": 97,
    "name": "Packaging material",
    "category": "Home Needs",
    "price": 0.0,
    "originalPrice": 0.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 379,
    "bestseller": false,
    "featured": false,
    "description": "Packaging material is a reliable and good quality product for everyday use.",
    "unit": "g"
  },
  {
    "id": 98,
    "name": "Maaza 600ml",
    "category": "Home Needs",
    "price": 40.0,
    "originalPrice": 40.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 336,
    "bestseller": false,
    "featured": false,
    "description": "Maaza 600ml is a reliable and good quality product for everyday use.",
    "unit": "ml"
  },
  {
    "id": 99,
    "name": "Chicken Karahi (Half)",
    "category": "Home Needs",
    "price": 320.0,
    "originalPrice": 320.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 433,
    "bestseller": false,
    "featured": false,
    "description": "Chicken Karahi (Half) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 100,
    "name": "Atta (ganeshphog)",
    "category": "Home Needs",
    "price": 36.0,
    "originalPrice": 36.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.5,
    "reviews": 390,
    "bestseller": false,
    "featured": false,
    "description": "Atta (ganeshphog) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 101,
    "name": "Thumsup 2l",
    "category": "Home Needs",
    "price": 90.0,
    "originalPrice": 90.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 221,
    "bestseller": false,
    "featured": false,
    "description": "Thumsup 2l is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 102,
    "name": "Mangrela",
    "category": "Home Needs",
    "price": 5.0,
    "originalPrice": 5.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 196,
    "bestseller": false,
    "featured": false,
    "description": "Mangrela is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 103,
    "name": "Maida (loose)",
    "category": "Home Needs",
    "price": 40.0,
    "originalPrice": 40.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.0,
    "reviews": 446,
    "bestseller": false,
    "featured": false,
    "description": "Maida (loose) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 104,
    "name": "Chat masala (rakesh)",
    "category": "Home Needs",
    "price": 10.0,
    "originalPrice": 10.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 309,
    "bestseller": false,
    "featured": false,
    "description": "Chat masala (rakesh) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 105,
    "name": "Peanut (badam)",
    "category": "Home Needs",
    "price": 140.0,
    "originalPrice": 140.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 476,
    "bestseller": false,
    "featured": false,
    "description": "Peanut (badam) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 106,
    "name": "Samosa (regular)",
    "category": "Home Needs",
    "price": 12.0,
    "originalPrice": 12.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 100,
    "bestseller": false,
    "featured": false,
    "description": "Samosa (regular) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 107,
    "name": "Jalebi",
    "category": "Home Needs",
    "price": 140.0,
    "originalPrice": 140.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 3.5,
    "reviews": 371,
    "bestseller": false,
    "featured": false,
    "description": "Jalebi is a reliable and good quality product for everyday use.",
    "unit": "pc"
  },
  {
    "id": 108,
    "name": "Water Gallon (20liter)",
    "category": "Home Needs",
    "price": 15.0,
    "originalPrice": 15.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 5.0,
    "reviews": 152,
    "bestseller": false,
    "featured": false,
    "description": "Water Gallon (20liter) is a reliable and good quality product for everyday use.",
    "unit": "l"
  },
  {
    "id": 109,
    "name": "Samosa chat (Classic)",
    "category": "Home Needs",
    "price": 35.0,
    "originalPrice": 35.0,
    "discount": 0,
    "image": "https://onecallsolutionteghra.github.io/onecallsolution/default-product.png",
    "rating": 4.0,
    "reviews": 450,
    "bestseller": false,
    "featured": false,
    "description": "Samosa chat (Classic) is a reliable and good quality product for everyday use.",
    "unit": "pc"
  }
];