// products.js — FULL list generated from PDF inventory

const products = [
  {
    "id": 1,
    "name": "Pasta Masala (Rakesh)",
    "category": "Masala & Spices",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 22,
    "bestseller": false,
    "featured": false,
    "description": "Pasta Masala (Rakesh) is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 2,
    "name": "Dettol Original Soap",
    "category": "Personal Care",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 24,
    "bestseller": false,
    "featured": false,
    "description": "Dettol Original Soap is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 3,
    "name": "Margo Neem Soap",
    "category": "Personal Care",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 26,
    "bestseller": false,
    "featured": false,
    "description": "Margo Neem Soap is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 4,
    "name": "Lux Soap",
    "category": "Personal Care",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 28,
    "bestseller": false,
    "featured": false,
    "description": "Lux Soap is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 5,
    "name": "Lifebuoy Soap",
    "category": "Personal Care",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 30,
    "bestseller": false,
    "featured": false,
    "description": "Lifebuoy Soap is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 6,
    "name": "Exo Anti-Bacterial Dishwash Bar",
    "category": "Home Care",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 32,
    "bestseller": false,
    "featured": false,
    "description": "Exo Anti-Bacterial Dishwash Bar is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 7,
    "name": "Surf Excel Bar",
    "category": "Home Care",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 34,
    "bestseller": false,
    "featured": false,
    "description": "Surf Excel Bar is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 8,
    "name": "Closeup Toothpaste",
    "category": "Personal Care",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 36,
    "bestseller": false,
    "featured": false,
    "description": "Closeup Toothpaste is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 9,
    "name": "Maggi Noodles",
    "category": "Instant Food",
    "price": 7,
    "originalPrice": 7,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 38,
    "bestseller": false,
    "featured": false,
    "description": "Maggi Noodles is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 10,
    "name": "Dabur Tooth Powder",
    "category": "Personal Care",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 40,
    "bestseller": false,
    "featured": false,
    "description": "Dabur Tooth Powder is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 11,
    "name": "Nihar Gold Hair Oil",
    "category": "Personal Care",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 42,
    "bestseller": false,
    "featured": false,
    "description": "Nihar Gold Hair Oil is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 12,
    "name": "Tata Iodised Salt",
    "category": "Grocery",
    "price": 30,
    "originalPrice": 30,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 44,
    "bestseller": false,
    "featured": false,
    "description": "Tata Iodised Salt is a reliable and good quality product for everyday use.",
    "unit": "kg"
  },
  {
    "id": 13,
    "name": "Goyal Gold Salt 500g",
    "category": "Grocery",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 46,
    "bestseller": false,
    "featured": false,
    "description": "Goyal Gold Salt 500g is a reliable and good quality product for everyday use.",
    "unit": "500g"
  },
  {
    "id": 14,
    "name": "Nisha Hair Color Shampoo Black",
    "category": "Personal Care",
    "price": 20,
    "originalPrice": 20,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 48,
    "bestseller": false,
    "featured": false,
    "description": "Nisha Hair Color Shampoo Black is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 15,
    "name": "Nisha Powder Hair Colour",
    "category": "Personal Care",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 50,
    "bestseller": false,
    "featured": false,
    "description": "Nisha Powder Hair Colour is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 16,
    "name": "Godrej Rich Creame Black",
    "category": "Personal Care",
    "price": 15,
    "originalPrice": 15,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 52,
    "bestseller": false,
    "featured": false,
    "description": "Godrej Rich Creame Black is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 17,
    "name": "Ginger Garlic Paste (Catch)",
    "category": "Grocery",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 54,
    "bestseller": false,
    "featured": false,
    "description": "Ginger Garlic Paste (Catch) is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 18,
    "name": "Whole Garam Masala",
    "category": "Masala & Spices",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 56,
    "bestseller": false,
    "featured": false,
    "description": "Whole Garam Masala is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 19,
    "name": "Pro-Ease XL Sanitary Pads (6 pads)",
    "category": "Personal Care",
    "price": 40,
    "originalPrice": 40,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 58,
    "bestseller": false,
    "featured": false,
    "description": "Pro-Ease XL Sanitary Pads (6 pads) is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 20,
    "name": "Darshan Pancham Incense Sticks",
    "category": "Pooja Items",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 60,
    "bestseller": false,
    "featured": false,
    "description": "Darshan Pancham Incense Sticks is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 21,
    "name": "Laxman Rekha",
    "category": "Home Care",
    "price": 20,
    "originalPrice": 20,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 62,
    "bestseller": false,
    "featured": false,
    "description": "Laxman Rekha is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 22,
    "name": "Atta (Ganeshbhog)",
    "category": "Grocery",
    "price": 36,
    "originalPrice": 36,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 64,
    "bestseller": false,
    "featured": false,
    "description": "Atta (Ganeshbhog) is a reliable and good quality product for everyday use.",
    "unit": "kg"
  },
  {
    "id": 23,
    "name": "Lambu",
    "category": "fast-food",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 66,
    "bestseller": false,
    "featured": false,
    "description": "Lambu is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 24,
    "name": "Director Pan Masala",
    "category": "Pan Masala",
    "price": 12,
    "originalPrice": 12,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 68,
    "bestseller": false,
    "featured": false,
    "description": "Director Pan Masala is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 25,
    "name": "Milk (Sudha) 500ml",
    "category": "Dairy",
    "price": 30,
    "originalPrice": 30,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 70,
    "bestseller": false,
    "featured": false,
    "description": "Milk (Sudha) 500ml is a reliable and good quality product for everyday use.",
    "unit": "500ml"
  },
  {
    "id": 26,
    "name": "Tasty Vermicelli (Sebai)",
    "category": "Grocery",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 72,
    "bestseller": false,
    "featured": false,
    "description": "Tasty Vermicelli (Sebai) is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 27,
    "name": "Soya Chunks (Simran)",
    "category": "Grocery",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 74,
    "bestseller": false,
    "featured": false,
    "description": "Soya Chunks (Simran) is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 28,
    "name": "Masoor Dal Small",
    "category": "Grocery",
    "price": 50,
    "originalPrice": 50,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 76,
    "bestseller": false,
    "featured": false,
    "description": "Masoor Dal Small is a reliable and good quality product for everyday use.",
    "unit": "0.5kg"
  },
  {
    "id": 29,
    "name": "Taaza Tea",
    "category": "Beverages",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 78,
    "bestseller": false,
    "featured": false,
    "description": "Taaza Tea is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 30,
    "name": "Surf Excel Powder 75g",
    "category": "Home Care",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 80,
    "bestseller": false,
    "featured": false,
    "description": "Surf Excel Powder 75g is a reliable and good quality product for everyday use.",
    "unit": "75g"
  },
  {
    "id": 31,
    "name": "Sugar",
    "category": "Grocery",
    "price": 48,
    "originalPrice": 48,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 82,
    "bestseller": false,
    "featured": false,
    "description": "Sugar is a reliable and good quality product for everyday use.",
    "unit": "kg"
  },
  {
    "id": 32,
    "name": "Mishri",
    "category": "Grocery",
    "price": 70,
    "originalPrice": 70,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 84,
    "bestseller": false,
    "featured": false,
    "description": "Mishri is a reliable and good quality product for everyday use.",
    "unit": "kg"
  },
  {
    "id": 33,
    "name": "Mentho Plus",
    "category": "Confectionery",
    "price": 2,
    "originalPrice": 2,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 86,
    "bestseller": false,
    "featured": false,
    "description": "Mentho Plus is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 34,
    "name": "Hansaplast Antiseptic Bandage",
    "category": "Medical",
    "price": 2.5,
    "originalPrice": 2.5,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 88,
    "bestseller": false,
    "featured": false,
    "description": "Hansaplast Antiseptic Bandage is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 35,
    "name": "Coolex Toothbrush",
    "category": "Personal Care",
    "price": 30,
    "originalPrice": 30,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 90,
    "bestseller": false,
    "featured": false,
    "description": "Coolex Toothbrush is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 36,
    "name": "Navratna Oil",
    "category": "Personal Care",
    "price": 1,
    "originalPrice": 1,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 92,
    "bestseller": false,
    "featured": false,
    "description": "Navratna Oil is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 37,
    "name": "Himgange Oil",
    "category": "Personal Care",
    "price": 1,
    "originalPrice": 1,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 94,
    "bestseller": false,
    "featured": false,
    "description": "Himgange Oil is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 38,
    "name": "Chand Tara Hard Gul",
    "category": "Personal Care",
    "price": 2,
    "originalPrice": 2,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 96,
    "bestseller": false,
    "featured": false,
    "description": "Chand Tara Hard Gul is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 39,
    "name": "Milk (Sudha) 1L",
    "category": "Dairy",
    "price": 58,
    "originalPrice": 58,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 98,
    "bestseller": false,
    "featured": false,
    "description": "Milk (Sudha) 1L is a reliable and good quality product for everyday use.",
    "unit": "1L"
  },
  {
    "id": 40,
    "name": "Dahi (Sudha) 80g",
    "category": "Dairy",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 100,
    "bestseller": false,
    "featured": false,
    "description": "Dahi (Sudha) 80g is a reliable and good quality product for everyday use.",
    "unit": "80g"
  },
  {
    "id": 41,
    "name": "Lassi (Sudha) 140ml",
    "category": "Dairy",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 102,
    "bestseller": false,
    "featured": false,
    "description": "Lassi (Sudha) 140ml is a reliable and good quality product for everyday use.",
    "unit": "140ml"
  },
  {
    "id": 42,
    "name": "Sprite Zero Sugar 250ml",
    "category": "Beverages",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 104,
    "bestseller": false,
    "featured": false,
    "description": "Sprite Zero Sugar 250ml is a reliable and good quality product for everyday use.",
    "unit": "250ml"
  },
  {
    "id": 43,
    "name": "Coca-Cola Zero Sugar 250ml",
    "category": "Beverages",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 106,
    "bestseller": false,
    "featured": false,
    "description": "Coca-Cola Zero Sugar 250ml is a reliable and good quality product for everyday use.",
    "unit": "250ml"
  },
  {
    "id": 44,
    "name": "Maaza 125ml",
    "category": "Beverages",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 108,
    "bestseller": false,
    "featured": false,
    "description": "Maaza 125ml is a reliable and good quality product for everyday use.",
    "unit": "125ml"
  },
  {
    "id": 45,
    "name": "Bisleri Water 500ml",
    "category": "Beverages",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 110,
    "bestseller": false,
    "featured": false,
    "description": "Bisleri Water 500ml is a reliable and good quality product for everyday use.",
    "unit": "500ml"
  },
  {
    "id": 46,
    "name": "Bisleri Water 1L",
    "category": "Beverages",
    "price": 20,
    "originalPrice": 20,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 112,
    "bestseller": false,
    "featured": false,
    "description": "Bisleri Water 1L is a reliable and good quality product for everyday use.",
    "unit": "1L"
  },
  {
    "id": 47,
    "name": "Rabri (Sudha) 80g",
    "category": "Dairy",
    "price": 20,
    "originalPrice": 20,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 114,
    "bestseller": false,
    "featured": false,
    "description": "Rabri (Sudha) 80g is a reliable and good quality product for everyday use.",
    "unit": "80g"
  },
  {
    "id": 48,
    "name": "Jaggery (Gur)",
    "category": "Grocery",
    "price": 60,
    "originalPrice": 60,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 116,
    "bestseller": false,
    "featured": false,
    "description": "Jaggery (Gur) is a reliable and good quality product for everyday use.",
    "unit": "kg"
  },
  {
    "id": 49,
    "name": "Silver Pearls",
    "category": "Confectionery",
    "price": 1,
    "originalPrice": 1,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 118,
    "bestseller": false,
    "featured": false,
    "description": "Silver Pearls is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 50,
    "name": "Raj Niwas Pan Masala",
    "category": "Pan Masala",
    "price": 6,
    "originalPrice": 6,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 120,
    "bestseller": false,
    "featured": false,
    "description": "Raj Niwas Pan Masala is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 51,
    "name": "Vimal Pan Masala",
    "category": "Pan Masala",
    "price": 6,
    "originalPrice": 6,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 122,
    "bestseller": false,
    "featured": false,
    "description": "Vimal Pan Masala is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 52,
    "name": "Shikhar Pan Masala",
    "category": "Pan Masala",
    "price": 6,
    "originalPrice": 6,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 124,
    "bestseller": false,
    "featured": false,
    "description": "Shikhar Pan Masala is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 53,
    "name": "Rajnigandha With Tulsi",
    "category": "Pan Masala",
    "price": 25,
    "originalPrice": 25,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 126,
    "bestseller": false,
    "featured": false,
    "description": "Rajnigandha With Tulsi is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 54,
    "name": "Gold Flake Cigarette",
    "category": "Tobacco",
    "price": 12,
    "originalPrice": 12,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 128,
    "bestseller": false,
    "featured": false,
    "description": "Gold Flake Cigarette is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 55,
    "name": "Charms Cigarette",
    "category": "Tobacco",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 130,
    "bestseller": false,
    "featured": false,
    "description": "Charms Cigarette is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 56,
    "name": "Kurkure",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 132,
    "bestseller": false,
    "featured": false,
    "description": "Kurkure is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 57,
    "name": "Takatak",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 134,
    "bestseller": false,
    "featured": false,
    "description": "Takatak is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 58,
    "name": "Diamond Katori",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 136,
    "bestseller": false,
    "featured": false,
    "description": "Diamond Katori is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 59,
    "name": "Lays Chips Green",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 138,
    "bestseller": false,
    "featured": false,
    "description": "Lays Chips Green is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 60,
    "name": "Haldiram Bhujia",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 140,
    "bestseller": false,
    "featured": false,
    "description": "Haldiram Bhujia is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 61,
    "name": "GME Diet Chiwda",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 142,
    "bestseller": false,
    "featured": false,
    "description": "GME Diet Chiwda is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 62,
    "name": "Haldiram Punjabi Tadka",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 144,
    "bestseller": false,
    "featured": false,
    "description": "Haldiram Punjabi Tadka is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 63,
    "name": "Kheerwala Chawal (Mafia)",
    "category": "Grocery",
    "price": 160,
    "originalPrice": 160,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 146,
    "bestseller": false,
    "featured": false,
    "description": "Kheerwala Chawal (Mafia) is a reliable and good quality product for everyday use.",
    "unit": "kg"
  },
  {
    "id": 64,
    "name": "Hajmola Regular",
    "category": "Digestive",
    "price": 1,
    "originalPrice": 1,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 148,
    "bestseller": false,
    "featured": false,
    "description": "Hajmola Regular is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 65,
    "name": "Hajmola Chat Cola",
    "category": "Digestive",
    "price": 1,
    "originalPrice": 1,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 150,
    "bestseller": false,
    "featured": false,
    "description": "Hajmola Chat Cola is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 66,
    "name": "Panchphoran",
    "category": "Masala & Spices",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 152,
    "bestseller": false,
    "featured": false,
    "description": "Panchphoran is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 67,
    "name": "Haldi Powder (Rakesh)",
    "category": "Masala & Spices",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 154,
    "bestseller": false,
    "featured": false,
    "description": "Haldi Powder (Rakesh) is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 68,
    "name": "Mirch Powder (Rakesh)",
    "category": "Masala & Spices",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 156,
    "bestseller": false,
    "featured": false,
    "description": "Mirch Powder (Rakesh) is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 69,
    "name": "Dhaniya Powder (Rakesh)",
    "category": "Masala & Spices",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 158,
    "bestseller": false,
    "featured": false,
    "description": "Dhaniya Powder (Rakesh) is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 70,
    "name": "Chicken Masala (Rakesh)",
    "category": "Masala & Spices",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 160,
    "bestseller": false,
    "featured": false,
    "description": "Chicken Masala (Rakesh) is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 71,
    "name": "Garam Masala (Rakesh)",
    "category": "Masala & Spices",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 162,
    "bestseller": false,
    "featured": false,
    "description": "Garam Masala (Rakesh) is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 72,
    "name": "Meat Masala (Rakesh)",
    "category": "Masala & Spices",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 164,
    "bestseller": false,
    "featured": false,
    "description": "Meat Masala (Rakesh) is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 73,
    "name": "Sabzi Masala (Rakesh)",
    "category": "Masala & Spices",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 166,
    "bestseller": false,
    "featured": false,
    "description": "Sabzi Masala (Rakesh) is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 74,
    "name": "Chat Masala (Rakesh)",
    "category": "Masala & Spices",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 168,
    "bestseller": false,
    "featured": false,
    "description": "Chat Masala (Rakesh) is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 75,
    "name": "Dove Shampoo + Conditioner",
    "category": "Personal Care",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 170,
    "bestseller": false,
    "featured": false,
    "description": "Dove Shampoo + Conditioner is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 76,
    "name": "Potato 1kg",
    "category": "Vegetables",
    "price": 15,
    "originalPrice": 15,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 172,
    "bestseller": false,
    "featured": false,
    "description": "Potato 1kg is a reliable and good quality product for everyday use.",
    "unit": "kg"
  },
  {
    "id": 77,
    "name": "Onion 2.5kg",
    "category": "Vegetables",
    "price": 60,
    "originalPrice": 60,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 174,
    "bestseller": false,
    "featured": false,
    "description": "Onion 2.5kg is a reliable and good quality product for everyday use.",
    "unit": "2.5kg"
  },
  {
    "id": 78,
    "name": "King's Mustard Oil 1L",
    "category": "Edible Oil",
    "price": 170,
    "originalPrice": 170,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 176,
    "bestseller": false,
    "featured": false,
    "description": "King's Mustard Oil 1L is a reliable and good quality product for everyday use.",
    "unit": "1L"
  },
  {
    "id": 79,
    "name": "Mustard Oil Loose",
    "category": "Edible Oil",
    "price": 0.2,
    "originalPrice": 0.2,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 178,
    "bestseller": false,
    "featured": false,
    "description": "Mustard Oil Loose is a reliable and good quality product for everyday use.",
    "unit": "ml"
  },
  {
    "id": 80,
    "name": "Lighter",
    "category": "Accessories",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 180,
    "bestseller": false,
    "featured": false,
    "description": "Lighter is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 81,
    "name": "Stove Lighter",
    "category": "Accessories",
    "price": 20,
    "originalPrice": 20,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 182,
    "bestseller": false,
    "featured": false,
    "description": "Stove Lighter is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 82,
    "name": "Tap",
    "category": "Hardware",
    "price": 20,
    "originalPrice": 20,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 184,
    "bestseller": false,
    "featured": false,
    "description": "Tap is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 83,
    "name": "Bonne Silicone Nipple",
    "category": "Baby Care",
    "price": 15,
    "originalPrice": 15,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 186,
    "bestseller": false,
    "featured": false,
    "description": "Bonne Silicone Nipple is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 84,
    "name": "Mamypoko Pants Diaper Small",
    "category": "Baby Care",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 188,
    "bestseller": false,
    "featured": false,
    "description": "Mamypoko Pants Diaper Small is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 85,
    "name": "Gillette Blade Pack 5pcs",
    "category": "Personal Care",
    "price": 15,
    "originalPrice": 15,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 190,
    "bestseller": false,
    "featured": false,
    "description": "Gillette Blade Pack 5pcs is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 86,
    "name": "RK Blade Pack 10pcs",
    "category": "Personal Care",
    "price": 15,
    "originalPrice": 15,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 192,
    "bestseller": false,
    "featured": false,
    "description": "RK Blade Pack 10pcs is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 87,
    "name": "Tata Tea Agni",
    "category": "Beverages",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 194,
    "bestseller": false,
    "featured": false,
    "description": "Tata Tea Agni is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 88,
    "name": "Colgate Toothpaste",
    "category": "Personal Care",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 196,
    "bestseller": false,
    "featured": false,
    "description": "Colgate Toothpaste is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 89,
    "name": "Head & Shoulders Shampoo",
    "category": "Personal Care",
    "price": 2,
    "originalPrice": 2,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 198,
    "bestseller": false,
    "featured": false,
    "description": "Head & Shoulders Shampoo is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 90,
    "name": "Dove Shampoo",
    "category": "Personal Care",
    "price": 2,
    "originalPrice": 2,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 200,
    "bestseller": false,
    "featured": false,
    "description": "Dove Shampoo is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 91,
    "name": "Clinic Plus Shampoo",
    "category": "Personal Care",
    "price": 1,
    "originalPrice": 1,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 202,
    "bestseller": false,
    "featured": false,
    "description": "Clinic Plus Shampoo is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 92,
    "name": "Papad (Choudhary)",
    "category": "Grocery",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 204,
    "bestseller": false,
    "featured": false,
    "description": "Papad (Choudhary) is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 93,
    "name": "Himalayan Pink Salt 100g",
    "category": "Grocery",
    "price": 15,
    "originalPrice": 15,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 206,
    "bestseller": false,
    "featured": false,
    "description": "Himalayan Pink Salt 100g is a reliable and good quality product for everyday use.",
    "unit": "100g"
  },
  {
    "id": 94,
    "name": "Sabudana",
    "category": "Grocery",
    "price": 25,
    "originalPrice": 25,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 208,
    "bestseller": false,
    "featured": false,
    "description": "Sabudana is a reliable and good quality product for everyday use.",
    "unit": "kg"
  },
  {
    "id": 95,
    "name": "Happy Happy Biscuit",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 210,
    "bestseller": false,
    "featured": false,
    "description": "Happy Happy Biscuit is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 96,
    "name": "2 in 1 Biscuit Anmol",
    "category": "Snacks",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 212,
    "bestseller": false,
    "featured": false,
    "description": "2 in 1 Biscuit Anmol is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 97,
    "name": "Parle-G Gluco Biscuit",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 214,
    "bestseller": false,
    "featured": false,
    "description": "Parle-G Gluco Biscuit is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 98,
    "name": "Magix Orange Biscuit",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 216,
    "bestseller": false,
    "featured": false,
    "description": "Magix Orange Biscuit is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 99,
    "name": "Marie Gold Biscuit",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 218,
    "bestseller": false,
    "featured": false,
    "description": "Marie Gold Biscuit is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 100,
    "name": "Good Day Biscuit",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 220,
    "bestseller": false,
    "featured": false,
    "description": "Good Day Biscuit is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 101,
    "name": "Magix Elaichi Biscuit",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 222,
    "bestseller": false,
    "featured": false,
    "description": "Magix Elaichi Biscuit is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 102,
    "name": "Milk Bikis Biscuit",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 224,
    "bestseller": false,
    "featured": false,
    "description": "Milk Bikis Biscuit is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 103,
    "name": "Dream Lite Biscuit",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 226,
    "bestseller": false,
    "featured": false,
    "description": "Dream Lite Biscuit is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 104,
    "name": "Snake It Biscuit",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 228,
    "bestseller": false,
    "featured": false,
    "description": "Snake It Biscuit is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 105,
    "name": "Mom's Magic Biscuit",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 230,
    "bestseller": false,
    "featured": false,
    "description": "Mom's Magic Biscuit is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 106,
    "name": "Magix Chocolate Biscuit",
    "category": "Snacks",
    "price": 5,
    "originalPrice": 5,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 232,
    "bestseller": false,
    "featured": false,
    "description": "Magix Chocolate Biscuit is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 107,
    "name": "Godrej Good Knight Incense Sticks",
    "category": "Home Care",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 234,
    "bestseller": false,
    "featured": false,
    "description": "Godrej Good Knight Incense Sticks is a reliable and good quality product for everyday use.",
    "unit": "pack"
  },
  {
    "id": 108,
    "name": "Onion 1kg",
    "category": "Vegetables",
    "price": 25,
    "originalPrice": 25,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 236,
    "bestseller": false,
    "featured": false,
    "description": "Onion 1kg is a reliable and good quality product for everyday use.",
    "unit": "kg"
  },
  {
    "id": 109,
    "name": "Potato Red 2.5kg",
    "category": "Vegetables",
    "price": 35,
    "originalPrice": 35,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 238,
    "bestseller": false,
    "featured": false,
    "description": "Potato Red 2.5kg is a reliable and good quality product for everyday use.",
    "unit": "2.5kg"
  },
  {
    "id": 110,
    "name": "Wheel Surf 500g",
    "category": "Home Care",
    "price": 39,
    "originalPrice": 39,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 240,
    "bestseller": false,
    "featured": false,
    "description": "Wheel Surf 500g is a reliable and good quality product for everyday use.",
    "unit": "500g"
  },
  {
    "id": 111,
    "name": "Chana Dal",
    "category": "Pulses",
    "price": 90,
    "originalPrice": 90,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 242,
    "bestseller": false,
    "featured": false,
    "description": "Chana Dal is a reliable and good quality product for everyday use.",
    "unit": "kg"
  },
  {
    "id": 112,
    "name": "Electric Tape",
    "category": "Electrical",
    "price": 10,
    "originalPrice": 10,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 244,
    "bestseller": false,
    "featured": false,
    "description": "Electric Tape is a reliable and good quality product for everyday use.",
    "unit": "pcs"
  },
  {
    "id": 113,
    "name": "Ginger 100g",
    "category": "Vegetables",
    "price": 15,
    "originalPrice": 15,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 246,
    "bestseller": false,
    "featured": false,
    "description": "Ginger 100g is a reliable and good quality product for everyday use.",
    "unit": "100g"
  },
  {
    "id": 114,
    "name": "Haldi Powder Loose 250g",
    "category": "Masala & Spices",
    "price": 37.5,
    "originalPrice": 37.5,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 248,
    "bestseller": false,
    "featured": false,
    "description": "Haldi Powder Loose 250g is a reliable and good quality product for everyday use.",
    "unit": "250g"
  },
  {
    "id": 115,
    "name": "Jeera Loose 100g",
    "category": "Masala & Spices",
    "price": 40,
    "originalPrice": 40,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 250,
    "bestseller": false,
    "featured": false,
    "description": "Jeera Loose 100g is a reliable and good quality product for everyday use.",
    "unit": "100g"
  },
  {
    "id": 116,
    "name": "Chicken Biryani 500g",
    "category": "Ready Food",
    "price": 120,
    "originalPrice": 120,
    "discount": 0,
    "image": "blank",
    "rating": 4.1,
    "reviews": 252,
    "bestseller": false,
    "featured": false,
    "description": "Chicken Biryani 500g is a reliable and good quality product for everyday use.",
    "unit": "500g"
  },
  {
    "id": 117,
    "name": "Sprite 250ml",
    "category": "Beverages",
    "price": 22,
    "originalPrice": 22,
    "discount": 0,
    "image": "blank",
    "rating": 4.2,
    "reviews": 254,
    "bestseller": false,
    "featured": false,
    "description": "Sprite 250ml is a reliable and good quality product for everyday use.",
    "unit": "250ml"
  },
  {
    "id": 118,
    "name": "Paneer Dosa 1 Plate",
    "category": "Ready Food",
    "price": 120,
    "originalPrice": 120,
    "discount": 0,
    "image": "blank",
    "rating": 4.3,
    "reviews": 256,
    "bestseller": false,
    "featured": false,
    "description": "Paneer Dosa 1 Plate is a reliable and good quality product for everyday use.",
    "unit": "plate"
  },
  {
    "id": 119,
    "name": "Mustard Oil 500ml (King's)",
    "category": "Edible Oil",
    "price": 95,
    "originalPrice": 95,
    "discount": 0,
    "image": "blank",
    "rating": 4.4,
    "reviews": 258,
    "bestseller": false,
    "featured": false,
    "description": "Mustard Oil 500ml (King's) is a reliable and good quality product for everyday use.",
    "unit": "500ml"
  },
  {
    "id": 120,
    "name": "Jeera",
    "category": "Masala & Spices",
    "price": 400,
    "originalPrice": 400,
    "discount": 0,
    "image": "blank",
    "rating": 4.0,
    "reviews": 260,
    "bestseller": false,
    "featured": false,
    "description": "Jeera is a reliable and good quality product for everyday use.",
    "unit": "kg"
  }
];