// ============================================================
// products.js — All grocery product data for FreshBasket Store
// ============================================================

const products = [
  // ── VEGETABLES ──────────────────────────────────────────
  {
    id: 1,
    name: "Organic Tomatoes",
    category: "Vegetables",
    price: 45,
    originalPrice: 60,
    discount: 25,
    image: "",
    rating: 4.5,
    reviews: 128,
    bestseller: true,
    featured: true,
    description: "Fresh organic tomatoes grown without pesticides. Rich in antioxidants and vitamins. Perfect for salads, curries, and gravies.",
    unit: "500g"
  },
  {
    id: 2,
    name: "Fresh Spinach",
    category: "Vegetables",
    price: 30,
    originalPrice: 30,
    discount: 0,
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&q=80",
    rating: 4.3,
    reviews: 89,
    bestseller: false,
    featured: false,
    description: "Tender baby spinach leaves, freshly harvested. High in iron and folate. Great for palak dishes and smoothies.",
    unit: "250g"
  },
  {
    id: 3,
    name: "Broccoli",
    category: "Vegetables",
    price: 80,
    originalPrice: 100,
    discount: 20,
    image: "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=400&q=80",
    rating: 4.4,
    reviews: 67,
    bestseller: false,
    featured: true,
    description: "Crisp fresh broccoli packed with vitamin C and K. Ideal for stir-fries, soups, and steaming.",
    unit: "500g"
  },
  {
    id: 4,
    name: "Carrots",
    category: "Vegetables",
    price: 35,
    originalPrice: 40,
    discount: 12,
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&q=80",
    rating: 4.6,
    reviews: 152,
    bestseller: true,
    featured: false,
    description: "Crunchy orange carrots rich in beta-carotene. Perfect for juices, salads, and halwa.",
    unit: "500g"
  },
  {
    id: 5,
    name: "Green Bell Pepper",
    category: "Vegetables",
    price: 55,
    originalPrice: 65,
    discount: 15,
    image: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&q=80",
    rating: 4.2,
    reviews: 45,
    bestseller: false,
    featured: false,
    description: "Crisp green capsicum with a mild flavour. Perfect for stir-fries, pizzas, and stuffed dishes.",
    unit: "3 pcs"
  },
  {
    id: 6,
    name: "Onion",
    category: "Vegetables",
    price: 28,
    originalPrice: 35,
    discount: 20,
    image: "https://images.unsplash.com/photo-1508747703725-719777637510?w=400&q=80",
    rating: 4.7,
    reviews: 210,
    bestseller: true,
    featured: false,
    description: "Farm-fresh red onions with a pungent aroma. A kitchen staple for every Indian recipe.",
    unit: "1 kg"
  },

  // ── FRUITS ──────────────────────────────────────────────
  {
    id: 7,
    name: "Alphonso Mangoes",
    category: "Fruits",
    price: 250,
    originalPrice: 320,
    discount: 22,
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&q=80",
    rating: 4.9,
    reviews: 340,
    bestseller: true,
    featured: true,
    description: "Premium Alphonso mangoes from Ratnagiri. Incredibly sweet and aromatic. The king of mangoes.",
    unit: "6 pcs"
  },
  {
    id: 8,
    name: "Fresh Strawberries",
    category: "Fruits",
    price: 120,
    originalPrice: 150,
    discount: 20,
    image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&q=80",
    rating: 4.7,
    reviews: 198,
    bestseller: true,
    featured: true,
    description: "Juicy red strawberries hand-picked at peak ripeness. Perfect for desserts, smoothies, and eating fresh.",
    unit: "250g"
  },
  {
    id: 9,
    name: "Bananas",
    category: "Fruits",
    price: 40,
    originalPrice: 40,
    discount: 0,
    image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&q=80",
    rating: 4.5,
    reviews: 280,
    bestseller: false,
    featured: false,
    description: "Naturally ripened bananas rich in potassium and fibre. A quick energy snack for all ages.",
    unit: "6 pcs"
  },
  {
    id: 10,
    name: "Green Apples",
    category: "Fruits",
    price: 180,
    originalPrice: 220,
    discount: 18,
    image: "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400&q=80",
    rating: 4.4,
    reviews: 134,
    bestseller: false,
    featured: false,
    description: "Crisp Granny Smith green apples with a tart flavour. Rich in fibre and antioxidants.",
    unit: "4 pcs"
  },
  {
    id: 11,
    name: "Watermelon",
    category: "Fruits",
    price: 65,
    originalPrice: 80,
    discount: 19,
    image: "https://images.unsplash.com/photo-1563114773-84221bd62daa?w=400&q=80",
    rating: 4.6,
    reviews: 167,
    bestseller: false,
    featured: true,
    description: "Sweet and hydrating watermelon, perfect for hot summer days. 92% water content.",
    unit: "Per kg"
  },
  {
    id: 12,
    name: "Oranges",
    category: "Fruits",
    price: 90,
    originalPrice: 110,
    discount: 18,
    image: "https://images.unsplash.com/photo-1547514701-42782101795e?w=400&q=80",
    rating: 4.3,
    reviews: 112,
    bestseller: false,
    featured: false,
    description: "Juicy Nagpur oranges packed with Vitamin C. Perfect for fresh juice and eating.",
    unit: "6 pcs"
  },

  // ── DAIRY ───────────────────────────────────────────────
  {
    id: 13,
    name: "Full Cream Milk",
    category: "Dairy",
    price: 60,
    originalPrice: 60,
    discount: 0,
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&q=80",
    rating: 4.8,
    reviews: 420,
    bestseller: true,
    featured: true,
    description: "Fresh full cream cow milk, pasteurized and homogenized. Rich in calcium and protein.",
    unit: "1 Litre"
  },
  {
    id: 14,
    name: "Greek Yogurt",
    category: "Dairy",
    price: 75,
    originalPrice: 90,
    discount: 17,
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80",
    rating: 4.6,
    reviews: 203,
    bestseller: true,
    featured: false,
    description: "Thick and creamy Greek-style yogurt with live cultures. High in protein and probiotics.",
    unit: "400g"
  },
  {
    id: 15,
    name: "Paneer",
    category: "Dairy",
    price: 95,
    originalPrice: 110,
    discount: 14,
    image: "https://images.unsplash.com/photo-1631452180775-aff9f3e4e895?w=400&q=80",
    rating: 4.7,
    reviews: 310,
    bestseller: true,
    featured: true,
    description: "Fresh homemade-style paneer made from pure cow milk. Soft, creamy, and protein-rich.",
    unit: "200g"
  },
  {
    id: 16,
    name: "Cheddar Cheese",
    category: "Dairy",
    price: 180,
    originalPrice: 210,
    discount: 14,
    image: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&q=80",
    rating: 4.4,
    reviews: 98,
    bestseller: false,
    featured: false,
    description: "Aged cheddar with a sharp, nutty flavour. Perfect for sandwiches, burgers, and pasta.",
    unit: "200g"
  },

  // ── SNACKS ──────────────────────────────────────────────
  {
    id: 17,
    name: "Baked Potato Chips",
    category: "Snacks",
    price: 40,
    originalPrice: 50,
    discount: 20,
    image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=400&q=80",
    rating: 4.3,
    reviews: 185,
    bestseller: false,
    featured: false,
    description: "Light and crispy baked potato chips with sea salt. 30% less fat than regular chips.",
    unit: "100g"
  },
  {
    id: 18,
    name: "Trail Mix",
    category: "Snacks",
    price: 150,
    originalPrice: 180,
    discount: 17,
    image: "https://images.unsplash.com/photo-1599599810694-b5b37304c041?w=400&q=80",
    rating: 4.5,
    reviews: 77,
    bestseller: false,
    featured: false,
    description: "Premium mix of almonds, cashews, raisins, and dark chocolate chips. Energy-packed healthy snack.",
    unit: "200g"
  },
  {
    id: 19,
    name: "Dark Chocolate",
    category: "Snacks",
    price: 130,
    originalPrice: 160,
    discount: 19,
    image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400&q=80",
    rating: 4.8,
    reviews: 256,
    bestseller: true,
    featured: true,
    description: "72% cocoa dark chocolate bar with antioxidants. Rich, intense flavour for chocolate lovers.",
    unit: "90g"
  },
  {
    id: 20,
    name: "Multigrain Crackers",
    category: "Snacks",
    price: 85,
    originalPrice: 95,
    discount: 11,
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&q=80",
    rating: 4.2,
    reviews: 63,
    bestseller: false,
    featured: false,
    description: "Crisp multigrain crackers made with oats, wheat, and seeds. Great with dips and cheese.",
    unit: "150g"
  },

  // ── BEVERAGES ───────────────────────────────────────────
  {
    id: 21,
    name: "Cold Brew Coffee",
    category: "Beverages",
    price: 110,
    originalPrice: 140,
    discount: 21,
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&q=80",
    rating: 4.7,
    reviews: 189,
    bestseller: true,
    featured: true,
    description: "Smooth and rich cold brew concentrate made from premium Arabica beans. 2x caffeine content.",
    unit: "300ml"
  },
  {
    id: 22,
    name: "Coconut Water",
    category: "Beverages",
    price: 55,
    originalPrice: 65,
    discount: 15,
    image: "https://images.unsplash.com/photo-1580657018950-c7f7d773465f?w=400&q=80",
    rating: 4.6,
    reviews: 143,
    bestseller: false,
    featured: false,
    description: "Natural tender coconut water with electrolytes. No added sugar. Nature's best sports drink.",
    unit: "200ml"
  },
  {
    id: 23,
    name: "Green Tea",
    category: "Beverages",
    price: 160,
    originalPrice: 200,
    discount: 20,
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",
    rating: 4.5,
    reviews: 221,
    bestseller: false,
    featured: false,
    description: "Premium Darjeeling green tea with natural antioxidants. Light floral notes and calming aroma.",
    unit: "25 bags"
  },
  {
    id: 24,
    name: "Fresh Orange Juice",
    category: "Beverages",
    price: 80,
    originalPrice: 80,
    discount: 0,
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&q=80",
    rating: 4.8,
    reviews: 302,
    bestseller: true,
    featured: true,
    description: "Cold-pressed fresh orange juice with no preservatives. 100% pure juice, full of Vitamin C.",
    unit: "500ml"
  }
];
